### ISSUE TITLE
Bug: No such file or directory: 'officialurl.json'

### ISSUE THREAD

**Issue by heyngra** [SpeedeKowskyy/mc-server-manager#2]
Bug happens after creating the server, and stopping it.
```python
Traceback (most recent call last):
  File "E:\Github\mc-server-manager\main.py", line 80, in <module>
    main()
  File "E:\Github\mc-server-manager\main.py", line 18, in main
    links = import_links()
  File "E:\Github\mc-server-manager\libs.py", line 4, in import_links
    with open("officialurl.json") as js:
FileNotFoundError: [Errno 2] No such file or directory: 'officialurl.json'
```

**Comment by SpeedeKowskyy** [comment]
Fixed
