### ISSUE TITLE
Bug: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by heyngra** [SpeedeKowskyy/mc-server-manager#3]
Bug happens, when you don't input any value for memory. Happens on both checks.
```python
Traceback (most recent call last):
  File "E:\Github\mc-server-manager\main.py", line 79, in <module>
    main()
  File "E:\Github\mc-server-manager\main.py", line 42, in main
    memory = int(input("How much memory do you want your server to have? (specify in MB) > "))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by heyngra** [comment]
fixed in: f02cd2be013e9f60ad28abec0410d6e7fd997a98
